title: 一些笔记
description: 一些笔记
author: YU000HONG
github: https://github.com/yu000hong
about: 持续学习，努力向前～
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-wechat
      link: "#"
    - icon: fa-weibo
      link: "https://weibo.com/u/yu000hong"
    - icon: fa-github
      link: "https://github.com/yu000hong"

urls:
    - text: 标签
      url: /tags
    - text: RSS
      url: /feed.xml

url: "https://yu000hong.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
permalink: /:year/:month/:day/:title.html
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
